### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by lfb0801** [dickensas/kotlin-gradle-templates#1]
I have been trying to use the [embed-python template](https://github.com/dickensas/kotlin-gradle-templates/tree/master/embed-python), but I have been having issues with running the project. Is there an option you could make the project run on an docker-based enviroment or add a part to the readme explaining how to setup the code on a new device?

**Comment by dickensas** [comment]
Sure, which version of linux you wanted to use, ubuntu? centos? fedora?

checkout the latest code

You can use this README for fresh device
[ReadMe for Ubuntu](https://github.com/dickensas/kotlin-gradle-templates/blob/master/embed-python/README.ubuntu.md)

**Mandatory Step**
in the build.gradle.kts
change mingwX64("libgnuplot") to mingwX64("libgnuplot1")
and change linuxX64("libgnuplot1") to linuxX64("libgnuplot")

that will work

**Comment by lfb0801** [comment]
Firstly, thanks for your response I wasn't even expecting a response😅.
Is there a way to forgo the mandatory step. And have `build.gradle.kts` be more generic?

My initial problem was based on insufficient dependecies. In my usecase I have multiple developers who can all work on different platforms(mostly windows, macos and linux distros), but in production the code is run on a docker environment, running ubuntu. Every member is explained the basic steps of running the docker env in development, but I would prefer to allow them to be able to run the project through their IDE's aswell.

I really appreciate the support you have given as of yet, if you prefer we can also continue this conversation via email.

**Comment by dickensas** [comment]
Yes, [Generic Muliplatform cinterops](https://github.com/JetBrains/kotlin-native/blob/master/samples/libcurl/build.gradle.kts)

in the above file mavenPublication, publishing, cleanLocalRepo-- are not required for our project

keep the hostTarget condition as per the above file so that our "libgnuplot" only occurs one time based on the current operating system

Example like below


      


    kotlin {
        // Determine host preset.
        val hostOs = System.getProperty("os.name")

       // Create target for the host platform.
       val hostTarget = when {
           hostOs == "Mac OS X" -> macosX64("libgnuplot")
           hostOs == "Linux" -> linuxX64("libgnuplot")
           hostOs.startsWith("Windows") -> mingwX64("libgnuplot")
           else -> throw GradleException("Host OS '$hostOs' is not supported in Kotlin/Native $project.")
       }

**Comment by dickensas** [comment]
inactive

**Comment by lfb0801** [comment]
Excuse for the inactivity.
First off all, I want to excuse myself for the inactivity, I was given a side project and was trying to figure out what was wrong myself.
I hope you are still able and willing to help.

I have been getting unresolved reference errors.

This is what the code looks like on my local machine:
![image](https://user-images.githubusercontent.com/16375630/95744852-55da6000-0c94-11eb-936f-1aca654f7e1b.png)

I have also tried to use the following file to perform Continuous Intergration:
![image](https://user-images.githubusercontent.com/16375630/95748954-182d0580-0c9b-11eb-9baa-b176da004d7b.png)

This causes the following errors;
![image](https://user-images.githubusercontent.com/16375630/95753583-1f0b4680-0ca2-11eb-8a97-6627980769fb.png)

Have you got any clue how to fix these 2 issues?

ps. The scope of this project has changed to only needing to run on a windows system as long as CI passes.

**Comment by dickensas** [comment]
you python shared library is not located properly
modify the below file accordingly for you python shared library locations

embed-python/src/nativeInterop/cinterop/python.def

```
libraryPaths.linux = /lib /usr/lib /usr/lib/python3.8/config-3.8-x86_64-linux-gnu /usr/lib/x86_64-linux-gnu
linkerOpts.linux = -L/lib -L/usr/lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/python3.8/config-3.8-x86_64-linux-gnu -lpython3.8
compilerOpts.linux = -L/lib -L/usr/lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/python3.8/config-3.8-x86_64-linux-gnu -lpython3.8
```

in the above three lines you can see `-L` is sepecified
it is the C/C++ compiler argument to tell the `.a` or `.sa` or `.so` or `.o` files where located 
you need to modify the locations accordingly for your operating system and python version

**Comment by lfb0801** [comment]
So do you think it is the installation in the github actions file that causes the problem? Or should I only fix the python.def file?

**Comment by dickensas** [comment]
you can fix the python.def file and re-locate the shared libraries of python
