### ISSUE TITLE
Provide the gradlew scripts

### ISSUE THREAD

**Issue by mardukbp** [dickensas/kotlin-gradle-templates#2]
These templates are awesome! But I don't understand why you don't include the gradlew scripts, which allow one to get started using them. The point of these scripts is to have a reproducible build environment and you already included all the configuration files.

Thank you for undertaking this effort. I too want to use Kotlin/Native with many of these libraries and frameworks to create cross-platform applications.

**Comment by dickensas** [comment]
done
